spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.11.10.147:3306/tftdb
    username: ds50a
    password: softcamp1!

  jwt:
    key: softcamp@jwt.key
    live:
      atk: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true